# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Soulesidibe
tagline:          'android development, mobile, startup, tech, news, webs'
description:      'An android enthusiast'
url:              http://soulesidibe.github.io


author:
  name:           'Souleymane Sidibe'
  url:            https://twitter.com/soulesidibe

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole

pages_list:       
  Blog: '/blog'
  Feed: '/atom.xml'