# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Soulesidibe
tagline:          'An android enthusiast'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://soulesidibe.github.io

author:
  name:           'Souleymane Sidibe'
  url:            https://twitter.com/soulesidibe

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'