# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Soulesidibe
tagline:          'android development, backend, Play!, mobile, startup, tech, news, web'
description:      'An android enthusiast'
url:              http://soulesidibe.github.io


author:
  name:           'Souleymane Sidibe'
  url:            https://twitter.com/soulesidibe

#paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Feed: '/atom.xml'
